services:
  - type: web
    name: aquavision-web
    env: docker
    plan: standard # The 'standard' plan provides 2GB RAM which PyTorch/OpenCV needs. 'Free' tier (512MB) will crash on Model Load.
    region: ohio
    envVars:
      - key: PORT
        value: 5000
    disk:
      name: aquavision-data
      mountPath: /app/static
      sizeGB: 1
